# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/Dapr/bindings/dotnet-sdk"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Dapr/bindings/nodejs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Dapr/pubsub-programmatic/nodejs/consumer1"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Dapr/pubsub-programmatic/nodejs/consumer2"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Dapr/pubsub-programmatic/nodejs/publisher"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Dapr/serviceinvocation/nodejs/httpbackendservice"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Dapr/serviceinvocation/nodejs/httpfrontendservice"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Dapr/state-management/nodejs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/ManagedIdentity/dotnet"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/ManagedIdentity/python/system-assigned"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/ManagedIdentity/python/user-assigned"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Resiliency/appresiliency-dotnet"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Resiliency/client-nodejs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Resiliency/daprresiliency-dotnet"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Resiliency/grpcappresiliency-dotnet"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/RuleBasedRouting/backendapp1"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/RuleBasedRouting/backendapp2"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/ShowRequestHeaders"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Storage/AzureFiles/ARM"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Storage/AzureFiles/Bicep"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/TCP/nodejs/tcpclient"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/TCP/nodejs/tcpservice"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/githubactionssample"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/grpc/python"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/multicontainer/nodejs/container1"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/multicontainer/nodejs/container2"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/Dapr/bindings/nodejs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/Dapr/pubsub-programmatic/nodejs/consumer1"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/Dapr/pubsub-programmatic/nodejs/consumer2"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/Dapr/pubsub-programmatic/nodejs/publisher"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/Dapr/serviceinvocation/nodejs/httpbackendservice"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/Dapr/serviceinvocation/nodejs/httpfrontendservice"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/Dapr/state-management/nodejs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/Resiliency/client-nodejs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/RuleBasedRouting/backendapp1"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/RuleBasedRouting/backendapp2"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/Storage/AzureFiles/ARM"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/Storage/AzureFiles/Bicep"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/TCP/nodejs/tcpclient"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/TCP/nodejs/tcpservice"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/githubactionssample"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/multicontainer/nodejs/container1"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/multicontainer/nodejs/container2"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/Dapr/actors/dotnet-sdk/MyActor.Interfaces"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/Dapr/actors/dotnet-sdk/MyActorClient"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/Dapr/actors/dotnet-sdk/MyActorService"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/Dapr/bindings/dotnet-sdk/binding-example-dotnet-sdk"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/ManagedIdentity/dotnet/ManagedIdentity"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/Resiliency/appresiliency-dotnet/Resiliency"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/Resiliency/daprresiliency-dotnet/daprapp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/Resiliency/grpcappresiliency-dotnet/GrpcService"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/ShowRequestHeaders/ShowRequestHeaders"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/ManagedIdentity/python/system-assigned"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/ManagedIdentity/python/user-assigned"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/TerraForm/AdminCredentials"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/TerraForm/SystemAssignedIdentity"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/TerraForm/SystemAssignedIdentity/default"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/TerraForm/UserAssignedIdentity"
    schedule:
      interval: "weekly"
