RESOURCE_GROUP="resourcegroup"
CONTAINERAPPS_ENVIRONMENT="containerappenvironment"
LOCATION="eastus"
AZURE_CONTAINER_REGISTRY="mycontainerregistry.azurecr.io"
AZURE_CONTAINER_REGISTRY_USERNAME="mycontainerregistry"
AZURE_CONTAINER_REGISTRY_PASSWORD="password"
KEY_VAULT_NAME="yourkeyvault"
SECRET_NAME="yoursecret"
