apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mybindingforoutput
  namespace: default
spec:
  type: bindings.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379