location: <RegionName>  
type: Microsoft.App/containerApps 
properties: 
  managedEnvironmentId: /subscriptions/<SubscriptionId>/resourceGroups/<ResourceGroupName>/providers/Microsoft.App/managedEnvironments/<ContainerAppEnvironmentName>
  configuration:
    activeRevisionsMode: Multiple
    ingress:
      external: true
      allowInsecure: false 
      targetPort: 4000
  template:
    containers:
    - name: httpservice1nodejs
      image: docker.io/gfakedocker/multicontainerfrontendnodejs:latest
      env:
      - name: APP_PORT
        value: 4000
    - name: httpservice2nodejs
      image: docker.io/gfakedocker/multicontainerbackendnodejs:latest
      env:
      - name: APP_PORT
        value: 5000
